# Generated by Django 2.2.10 on 2021-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210324_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='document',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
