# Generated by Django 2.2.10 on 2021-03-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210324_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='document',
        ),
    ]
